import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true


[font]
normal.family = "Hack Nerd Font"

size = 11
